@startuml

hide circle
skinparam linetype ortho

entity Benchmark {
  *backup_pair_id: number
  --
  received_data_size_gb: number
}

entity BackupPair {
  *experiment_id: number <<FK>>
  *name string
  --
  data_size_gb: number
}

entity Experiment {
  *id: number <<generated>>
  --
  network_id: number <<FK>>
}

entity Network {
  *id: number <<generated>>
  --
  name: string
}

Benchmark |o--|| BackupPair
BackupPair }|--|| Experiment
Experiment }o--|| Network

@enduml
